// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSetRelayStateChange();
void onUseSensorChange();

float packVoltage;
float usbVolt;
int humidity;
int moisture;
int temperature;
bool setRelayState;
bool useSensor;

void initProperties(){

  ArduinoCloud.addProperty(packVoltage, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(usbVolt, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(moisture, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(setRelayState, READWRITE, ON_CHANGE, onSetRelayStateChange);
  ArduinoCloud.addProperty(useSensor, READWRITE, ON_CHANGE, onUseSensorChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);